// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Totaller is an autogenerated mock type for the Totaller type
type Totaller struct {
	mock.Mock
}

// Total provides a mock function with given fields: _a0
func (_m *Totaller) Total(_a0 ...int) int {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int
	if rf, ok := ret.Get(0).(func(...int) int); ok {
		r0 = rf(_a0...)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
